name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  clubhouse-token:  # id of input
    description: 'Clubhouse API token'
    required: true
  amplify-project-id:
    description: 'Project ID from the amplify console'
    required: true  
  event-payload:
    description: 'Project ID from the amplify console'
    required: true      
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'